// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 5);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1722585734);
user_pref("app.update.lastUpdateTime.region-update-timer", 1722585734);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1722585734);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1722585764);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1722585734);
user_pref("browser.region.update.updated", 1722585706);
user_pref("browser.search.region", "IN");
user_pref("calendar.caldav.googleResync", 1722585705);
user_pref("calendar.list.sortOrder", "bf7d4512-b4ab-4456-a346-4de6facc5d6f");
user_pref("calendar.registry.bf7d4512-b4ab-4456-a346-4de6facc5d6f.calendar-main-default", true);
user_pref("calendar.registry.bf7d4512-b4ab-4456-a346-4de6facc5d6f.calendar-main-in-composite", true);
user_pref("calendar.registry.bf7d4512-b4ab-4456-a346-4de6facc5d6f.disabled", true);
user_pref("calendar.registry.bf7d4512-b4ab-4456-a346-4de6facc5d6f.name", "Home");
user_pref("calendar.registry.bf7d4512-b4ab-4456-a346-4de6facc5d6f.type", "storage");
user_pref("calendar.registry.bf7d4512-b4ab-4456-a346-4de6facc5d6f.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1722585715102");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1727331229);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240903191356");
user_pref("extensions.lastAppVersion", "115.15.0");
user_pref("extensions.lastPlatformVersion", "115.15.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"bd4be4d1-aeba-42b3-9148-35794e8dd41c\",\"google@search.mozilla.org\":\"8022bee2-6382-45bb-8738-aabde2218c6e\",\"ddg@search.mozilla.org\":\"44647357-68de-46b2-b226-09f67a375579\",\"amazondotcom@search.mozilla.org\":\"58259a5f-f760-4b84-823e-6dfaf7e3ca30\",\"wikipedia@search.mozilla.org\":\"ea19275c-fbb5-40a4-9384-2140aabff845\",\"bing@search.mozilla.org\":\"5826a653-7869-4bd8-836b-78c298d3d903\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1722585885);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "526c336a-0a0e-4e34-8e69-abc4632d907");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.15.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1722585885);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -20737);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1722606472);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1722606472);
user_pref("services.settings.thunderbird.search-config.last_check", 1722606472);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1722606472);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1722585885);
user_pref("toolkit.startup.last_success", 1727331226);
user_pref("toolkit.telemetry.cachedClientID", "ad68bb93-0d6f-44ca-8733-12ef0955fb5b");
user_pref("toolkit.telemetry.previousBuildID", "20240903191356");
